### ISSUE TITLE
Launcher not detecting AOTR 2.9

### ISSUE THREAD

**Issue by dertroglodyt** [AnakinSklavenwalker/FoC-Mod-Launcher#16]
The launcher only shows the 2 vanilla starts (FOC, EAW).
AOTR 2.9 resides in C:\Program Files (x86)\Steam\steamapps\workshop\content\32470\1397421866
and can be startet via steam if I put the mod path in start parameters.

In case it helps:
Win10 Pro (german), Steam (Family account sharing enabled, changing loged in user does not change anything), Game language "english"

Btw: Thanks for your effort on this launcher.

**Comment by AnakinRaW** [comment]
Still an issue? 

Are other mods found?

**Comment by dertroglodyt** [comment]
Sorry, no idea, not playing this anymore.
